.TH "D:/projects/coding/C2H5OH/C2H5OH/C2H5OH.cpp" 3 "C2H5OH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/projects/coding/C2H5OH/C2H5OH/C2H5OH.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'precompile\&.hpp'\fP
.br
\fC#include 'Game\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for C2H5OH from the source code\&.
