.TH "D:/projects/coding/C2H5OH/C2H5OH/Enemy.hpp" 3 "C2H5OH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/projects/coding/C2H5OH/C2H5OH/Enemy.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'precompile\&.hpp'\fP
.br
\fC#include 'RenderObject\&.hpp'\fP
.br
\fC#include 'Player\&.hpp'\fP
.br
\fC#include 'Bullet\&.hpp'\fP
.br
\fC#include <semaphore>\fP
.br
\fC#include <mutex>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnemy\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Color \fBColorFromHSV\fP (float hue, float saturation, float value)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Color ColorFromHSV (float hue, float saturation, float value)"

.SH "Author"
.PP 
Generated automatically by Doxygen for C2H5OH from the source code\&.
