.TH "D:/projects/coding/C2H5OH/C2H5OH/Game.hpp" 3 "C2H5OH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/projects/coding/C2H5OH/C2H5OH/Game.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'precompile\&.hpp'\fP
.br
\fC#include 'Player\&.hpp'\fP
.br
\fC#include 'Square\&.hpp'\fP
.br
\fC#include 'Walker\&.hpp'\fP
.br
\fC#include 'RangedEnemy\&.hpp'\fP
.br
\fC#include 'Weapons\&.hpp'\fP
.br
\fC#include 'Enemy\&.hpp'\fP
.br
\fC#include 'Chest\&.hpp'\fP
.br
\fC#include 'Item\&.hpp'\fP
.br
\fC#include 'RectangleHitbox\&.hpp'\fP
.br
\fC#include 'RangedBoss\&.hpp'\fP
.br
\fC#include <thread>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGame\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFLAGS_MULTITHREADING\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FLAGS_MULTITHREADING"

.SH "Author"
.PP 
Generated automatically by Doxygen for C2H5OH from the source code\&.
