.TH "md__d_1_2projects_2coding_2_c2_h5_o_h_2_r_e_a_d_m_e" 3 "C2H5OH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__d_1_2projects_2coding_2_c2_h5_o_h_2_r_e_a_d_m_e \- README 
.PP

.PP
 
.br
 
.SH "📖 Description "
.PP
.PP
C2H5OH is our team name\&. Our goal is to create a game about Chemistry and Biology 
.SH "👥 Our Team "
.PP
.PP
.IP "1." 4
\fBStiliyan Mishev\fP - \fBScrum trainer\fP 
.br
 
.PP
.RS 4
\fI\fBGitHub profile\fP\fP: \fC\fI\fBSMMishev21\fP\fP\fP 
.br
 
.RE
.PP

.IP "2." 4
\fBIvailo Bachvarov\fP - \fBBackend Developer\fP 
.PP
.RS 4
\fI\fBGitHub profile\fP\fP: \fC\fI\fBISBachvarov21\fP\fP\fP 
.br
 
.RE
.PP

.IP "3." 4
\fBMartin Velkov\fP - \fBBackend Developer\fP 
.PP
.RS 4
\fI\fBGitHub profile\fP\fP: \fC\fI\fBMVVelkov21\fP\fP\fP 
.br
 
.RE
.PP

.IP "4." 4
\fBNikola Paskov\fP - \fBDesigner\fP 
.PP
.RS 4
\fI\fBGitHub profile\fP\fP: \fC\fI\fBNTPaskov21\fP\fP\fP 
.RE
.PP

.PP
.PP
.SH "🌐💻 Used technologies"
.PP
.PP
.PP
   <img src='https://upload\&.wikimedia\&.org/wikipedia/commons/thumb/b/bf/SFML2\&.svg/1280px-SFML2\&.svg\&.png' width='50'               
.PP
.SH "📋 Documents"
.PP
.PP
.SS "\fC📜 Documentation  📰 Presentation   @subsection autotoc_md0 \fI\fBIf you like our game you can give us a 🥇\fP\fP \fP"

