.TH "D:/projects/coding/C2H5OH/C2H5OH/RenderObject.cpp" 3 "C2H5OH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/projects/coding/C2H5OH/C2H5OH/RenderObject.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'precompile\&.hpp'\fP
.br
\fC#include 'RenderObject\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBclampMax\fP (float n, float lower, float upper)"
.br
.ti -1c
.RI "float \fBclampMin\fP (float n, float lower, float upper)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "float clampMax (float n, float lower, float upper)"

.SS "float clampMin (float n, float lower, float upper)"

.SH "Author"
.PP 
Generated automatically by Doxygen for C2H5OH from the source code\&.
